### ISSUE TITLE
Feature request: Clickable area around slider

### ISSUE THREAD

**Issue by probablykasper** [Stryzhevskyi/rangeSlider#27]
I would like to be able to click above/below the slider itself. For instance the YouTube's "progress bar" lets you click above where the actual red color is. I believe YouTube does this by having the slider itself, and then an element above it which adds the padding. I don't think the actual slider element is clickable, though I might be wrong.

One possible solution I can think of is to make the height go to where the slider should be clicked, then add a gradient which says the top/bottom parts of the slider should be transparent. At the same time, this will affect all the children, which means you have to change stuff for all of them as well.

Would be very nice to have an easy solution to this. Thanks.

**Comment by Stryzhevskyi** [comment]
Hi,
Why don't you add desirable feature with pure CSS?

```css
.rangeSlider::after {
    content: '';
    display: block;
    top: -30px;
    bottom: -30px;
    left: 0;
    right: 0;
    background: rgba(232, 5, 5, 0.2); /* 20% transparent for illustration purpose */
    position: absolute;
}
```
(example for horizontal slider)
![screencast 2017-10-14 22-56-49](https://user-images.githubusercontent.com/1058402/31578909-75d62200-b133-11e7-8677-c277709be268.gif)
